"""Add fields nome, sobrenome, email to User

Revision ID: 186fc6cc0ade
Revises: 20bd70ba5894
Create Date: 2025-05-22 23:53:43.219657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186fc6cc0ade'
down_revision = '20bd70ba5894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=124),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('sobrenome',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('sobrenome',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=124),
               nullable=True)

    # ### end Alembic commands ###
